spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onlineexam
    username: root
    password: 13791372
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update

    show-sql: true
application :
  security:
    login-address: localhost:8080/api/login
  constants:
    master-code-number: 7
    student-code-number: 7
    admin-code-number: 10
#server:
#  port: 8083